### ISSUE TITLE
Uncaught Error: No item 107 in vector of length 107

### ISSUE THREAD

**Issue by markzorkman** [oakmac/atom-parinfer#37]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Microsoft Windows 10 Home
**Thrown From**: [Parinfer](https://github.com/oakmac/atom-parinfer) package, v1.4.0

### Stack Trace

Uncaught Error: No item 107 in vector of length 107

```
At C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:11603

Error: No item 107 in vector of length 107
    at Error (native)
    at Object.cljs.core.vector_index_out_of_bounds (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:11603:9)
    at Object.cljs.core.array_for (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:11628:80)
    at [object Object].cljs.core.PersistentVector.cljs$core$IIndexed$_nth$arity$2 (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:11751:20)
    at Function.cljs.core.nth.cljs$core$IFn$_invoke$arity$2 (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:4791:14)
    at cljs.core.nth (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:4776:28)
    at C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:21983:99
    at atom_parinfer.core.find_start_row (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:21984:6)
    at atom_parinfer.core.apply_parinfer_STAR_ (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:22006:312)
    at atom_parinfer.core.apply_parinfer_BANG_ (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:22021:243)
    at d (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:8939:87)
    at c (C:\Users\markaddleman\.atom\packages\Parinfer\lib\atom-parinfer.js:8974:20)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.11.3
linter-clojure, v1.1.2
Parinfer, v1.4.0

# Dev
No dev packages
```

**Comment by oakmac** [comment]
Thank you for the report!

I think this is a problem with CRLF line endings and fixed with [v1.5.0](https://github.com/oakmac/atom-parinfer/releases/tag/v1.5.0).

Can you upgrade and let me know?

**Comment by markzorkman** [comment]
Thanks! I'll give it a try in a bit

**Comment by markzorkman** [comment]
Looks good.  Thanks!
