### ISSUE TITLE
Uncaught Error: No item 9 in vector of length 8

### ISSUE THREAD

**Issue by Ragnaroek** [oakmac/atom-parinfer#42]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: [Parinfer](https://github.com/oakmac/atom-parinfer) package, v1.5.0

### Stack Trace

Uncaught Error: No item 9 in vector of length 8

```
At /Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:11603

Error: No item 9 in vector of length 8
    at Error (native)
    at Object.cljs.core.vector_index_out_of_bounds (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:11603:9)
    at Object.cljs.core.array_for (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:11628:80)
    at [object Object].cljs.core.PersistentVector.cljs$core$IIndexed$_nth$arity$2 (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:11751:20)
    at Function.cljs.core.nth.cljs$core$IFn$_invoke$arity$2 (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:4791:14)
    at cljs.core.nth (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:4776:28)
    at /Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:21998:99
    at atom_parinfer.core.find_end_row (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:21999:6)
    at atom_parinfer.core.apply_parinfer_STAR_ (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:22006:336)
    at atom_parinfer.core.apply_parinfer_BANG_ (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:22021:243)
    at d (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:8939:87)
    at c (/Users/mb/.atom/packages/Parinfer/lib/atom-parinfer.js:8974:20)
```

### Commands

```
     -0:01.3.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
     -0:00.5.0 editor:newline (atom-text-editor.editor.is-focused.vim-mode-plus.insert-mode)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
Parinfer, v1.5.0
vim-mode-plus, v0.14.1

# Dev
No dev packages
```

**Comment by oakmac** [comment]
Think this should be fixed in [v1.6.0](https://github.com/oakmac/atom-parinfer/releases/tag/v1.6.0)

Can you update and let me know?

**Comment by Ragnaroek** [comment]
seems to work now. now execption all morning with the new version.

**Comment by shaunlebron** [comment]
thanks @Ragnaroek :+1:
